= Content Security Policy
:navtitle: Content Security Policy 
:title: Content Security Policy 
:page-toclevels: 4
:source-language: csharp 


== Introduction

Content Security Policy is delivered via a HTTP response header, much like HSTS, and defines approved sources of content that the browser may load.

A CSP header allows you to define approved sources for content on your site that the browser can load.

By specifying only those sources that you wish the browser to load content from, you can protect your visitors from a whole range of issues.

These apply to only responses that return one of the following content-types:

* `+text/html+`
* `+text/javascript+`
* `+application/javascript+` 

== Security Headers

Content Security Policy headers are added using the `+SecurityHeaderMiddleWare+` class.

`+AddFrameOptionsDeny+` - Adds X-Frame-Options DENY to all requests. The page cannot be displayed in a frame, regardless of the site attempting to do so.

`+AddXssProtectionBlock+` - Adds X-XSS-Protection 1; mode=block to all requests. Enables XSS protections and instructs the user-agent to block the response in the event that script has been inserted from user input, instead of sanitizing.

`+AddContentTypeOptionsNoSniff+` - Add X-Content-Type-Options nosniff to all requests. Disables content sniffing. Can be set to protect against MIME type confusion attacks.

`+AddStrictTransportSecurityMaxAge+` - Add Strict-Transport-Security max-age=maxAge to all requests. Tells the user-agent to cache the domain in the STS list for the number of seconds provided.

`+AddReferrerPolicyOriginWhenCrossOrigin+` - The browser will send the full URL to requests to the same origin but only send the origin when requests are cross-origin.

`+RemoveServerHeader+` - Removes the Server header from all responses.

== Content Security Policy Headers

* {empty}
+
[source, csharp]
----
builder.AddDefaultSrc().Self();
----
** `+AddDefaultSrc+` - The default-src directive serves as a fallback for the other CSP fetch directives.
** Valid sources include '`self`', '`unsafe-inline`', '`unsafe-eval`', '`none`', scheme such as http:, or internet hosts by name or IP address, as well as an optional URL scheme and/or port number.
** The site’s address may include an optional leading wildcard (the asterisk character, '`__’), and you may use a wildcard (again, ’__`') as the port number, indicating that all legal ports are valid for the source.

* {empty}
+
[source,csharp]
----
builder.AddConnectSrc().Self().From(stsUrl).From(socketUrl);
----
** `+AddConnectSrc+` - The '`connect-src`' directive restricts the URLs which can be loaded using script interfaces The APIs that are restricted are: `+<a>+`, `+ping+`, `+Fetch+`, `+XMLHttpRequest+`, `+WebSocket+`, and `+EventSource+`.
** `+Self+` - Allow sources from the origin from which the protected document is being served, including the same URL scheme and port number.
** `+From+` - Allow resources from the given uri. May be any non-empty value. In this case, we add the host url and the sts url to the list.

* {empty}
+
[source,csharp]
----
builder
    .AddFontSrc() // font-src 'self'
    .Self()
    .Data();
----
** `+AddFontSrc+` - The font-src directive specifies valid sources for fonts loaded using @font-face.
** `+Self+` - Allow sources from the origin from which the protected document is being served, including the same URL scheme and port number.
** `+Data+` - data: Allows data: URIs to be used as a content source.
+
WARNING: This is insecure; an attacker can also inject arbitrary data. Use this sparingly and definitely not for scripts.

* {empty}
+
[source,csharp]
----
builder
    .AddObjectSrc() // object-src 'none'
    .None();
----
** `+AddObjectSrc+` - The object-src directive specifies valid sources for the `+<object>+`, `+<embed>+`, and `+<applet>+` elements.
** `+None+` - Block the resource (Refers to the empty set; that is, no URLs match)

* {empty}
+
[source,csharp]
----
builder
    .AddFormAction() // form-action 'self'
    .Self();
----
** `+AddFormAction+` - The font-src directive specifies valid sources for fonts loaded using @font-face.
** `+Self+` - Allow sources from the origin from which the protected document is being served, including the same URL scheme and port number.

* {empty}
+
[source,csharp]
----
builder
    .AddImgSrc() // img-src https:
    .Self()
    .Data();
----
** `+AddImgSrc+` - he img-src directive specifies valid sources of images and favicons.
** `+Self+` - Allow sources from the origin from which the protected document is being served, including the same URL scheme and port number.
** `+Data+` - data: Allows data: URIs to be used as a content source.
+
WARNING: This is insecure; an attacker can also inject arbitrary data: URIs. Use this sparingly and definitely not for scripts.

* {empty}
+
[source,csharp]
----
 builder.AddCustomDirective(
                        "script-src",
                        "'self' 'unsafe-inline' 'unsafe-eval'");
                    builder.AddCustomDirective("style-src", "'self' 'unsafe-inline' 'unsafe-eval'");
builder.AddCustomDirective("style-src", "'self' 'unsafe-inline' 'unsafe-eval'");
----
** `+script-src+` - The script-src directive specifies valid sources for sources for JavaScript.
** `+style-src+` - The style-src directive specifies valid sources for sources for stylesheets.
** `+Self+` - Allow sources from the origin from which the protected document is being served, including the same URL scheme and port number.
** `+UnsafeInline+` - Allows the use of inline resources, such as inline `+<script>+` elements, inline event handlers, and inline `+<style>+` elements.
+
WARNING: This source is insecure - you should not use this directive if at all possible.
** `+UnsafeEval+` - Allows the use of eval() and similar methods for creating code from strings.
+
WARNING: This source is insecure - you should not use this directive if at all possible.

* {empty}
+
[source,csharp]
----
builder.AddUpgradeInsecureRequests();
----
** The upgrade-insecure-requests directive instructs user agents to treat all of a site’s insecure URLs (those served over HTTP) as though they have been replaced with secure URLs (those served over HTTPS).
** This directive is intended for websites with large numbers of insecure legacy URLs that need to be rewritten.

* {empty}
+
[source,csharp]
----
builder.AddMediaSrc().Self();
----
** `+AddMediaSrc+` - The media-src directive specifies valid sources for loading media using the `+<audio>+` and `+<video>+` elements.
** `+Self+` - Allow sources from the origin from which the protected document is being served, including the same URL scheme and port number.


* {empty}
+
[source,csharp]
----
builder.AddFrameAncestors().None();
----
** `+AddFrameAncestors+` - The frame-ancestors directive specifies valid parents that may embed a page using `+<frame>+`, `+<iframe>+`, `+<object>+`, `+<embed>+`, or `+<applet>+`.
** Setting this directive to '`none`' is similar to X-Frame-Options: DENY (which is also supported in older browsers).

* {empty}
+
[source,csharp]
----
builder.AddFrameSrc().From(stsUrl);
----
** `+AddFrameSrc+` - The frame-src directive specifies valid sources for nested browsing contexts loading using elements such as `+<frame>+` and `+<iframe>+`.
** `+From+` - Allow resources from the given uri. May be any non-empty value.

== References

* https://github.com/andrewlock/NetEscapades.AspNetCore.SecurityHeaders[NetEscapades.AspNetCore.SecurityHeaders]
* https://scotthelme.co.uk/content-security-policy-an-introduction/[Content
Security Policy]
* https://scotthelme.co.uk/csp-cheat-sheet/?ref=scotthelme.co.uk[CSP
Cheatsheet]
* https://scotthelme.co.uk/goodbye-feature-policy-and-hello-permissions-policy/[Permissions
Policy]
