site:
  title: AspNetCoreAngular Developer Documentation
  start_page: homesite::index.adoc
  url: https://tremorscript.com
content:
  sources:
  - url: ./
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: current
ui:
  bundle:
    # url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    url: ./ui-bundle.zip
    # snapshot: true
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files:
        - .nojekyll
    - path: .nojekyll
antora:
  extensions:
    - "@antora/lunr-extension"
